name: Build LibWrt Arthur

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 25.12-nss


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang \
            flex \
            bison \
            gawk \
            gettext \
            git \
            libncurses-dev \
            libssl-dev \
            python3 \
            rsync \
            unzip \
            zlib1g-dev \
            ccache


      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a


      - name: Find Arthur profile
        run: |
          echo "Search JDCloud device"

          make info | grep -i jdcloud

          PROFILE=$(make info | grep -i jdcloud | head -1 | awk '{print $1}')

          echo "PROFILE=$PROFILE"

          echo "PROFILE=$PROFILE" >> $GITHUB_ENV


      - name: Configure
        run: |
          echo "Using profile:"
          echo $PROFILE

          echo "CONFIG_TARGET_qualcommax=y" > .config
          echo "CONFIG_TARGET_qualcommax_ipq60xx=y" >> .config
          echo "$PROFILE=y" >> .config

          echo "CONFIG_PACKAGE_kmod-tun=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
          echo "CONFIG_TARGET_ROOTFS_SQUASHFS=y" >> .config

          make defconfig

          echo "===== CONFIG ====="
          grep -i jdcloud .config || true
          grep kmod-tun .config || true


      - name: Download
        run: |
          make download -j$(nproc)


      - name: Build
        run: |
          make -j$(nproc) || make -j1 V=s


      - name: Collect firmware
        run: |
          mkdir firmware

          find bin/targets \
          -type f \
          \( -name "*.bin" -o -name "*.itb" \) \
          -exec cp {} firmware/ \;


          ls -lh firmware


      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: LibWrt-Arthur-firmware
          path: firmware
